# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2b3d8ae0ba7ceea0e8999603a0f1a8ea83c43caf1b843c44f5c2b4c04c36d9287291d2d6841a91f55bdc1f09da87a30a1702212d5e4f9398173ee2d5bc8b703

test:
  secret_key_base: 8af5ce1ff2e2ee71e46d2be4f60fbe48444347e00a84bd76d40adb4dcf1d312f2cc34f326197f16ca55d414ae522f4b1808e69558fc12002b1119f2fe1680683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
